{
  try {
    verify(response,times(1)).sendError(404);
  }
 catch (  IOException e) {
    Assert.fail();
  }
}
